{{- if .Values.system.components.attendee_service.enable }}
{{ $attSrvInput := dict "name" "attendee-service"
                        "all" .Values
                        "component" .Values.system.components.attendee_service
                        "secrets" (list "REG_SECRET_DB_PASSWORD" "REG_SECRET_API_TOKEN")
                        "command" "/main"
                        "args" (list "--config=/config/config.yaml" "--migrate-database" "--ecs-json-logging") -}}
{{- template "helpers.deployment" $attSrvInput }}
---
{{- end }}
{{- if .Values.system.components.auth_service.enable }}
{{ $authSrvInput := dict "name" "auth-service"
                         "all" .Values
                         "component" .Values.system.components.auth_service
                         "secrets" (list "REG_SECRET_OIDC_CLIENT_ID" "REG_SECRET_OIDC_CLIENT_SECRET")
                         "command" "/main"
                         "args" (list "--config=/config/config.yaml" "--ecs-json-logging") -}}
{{- template "helpers.deployment" $authSrvInput }}
---
{{- end }}
{{- if .Values.system.components.mail_service.enable }}
{{ $mailSrvInput := dict "name" "mail-service"
                         "all" .Values
                         "component" .Values.system.components.mail_service
                         "secrets" (list "REG_SECRET_SMTP_PASSWORD" "REG_SECRET_DB_PASSWORD" "REG_SECRET_API_TOKEN")
                         "command" "/main"
                         "args" (list "--config=/config/config.yaml" "--migrate-database" "--ecs-json-logging") -}}
{{- template "helpers.deployment" $mailSrvInput }}
---
{{- end }}
{{- if .Values.system.components.payment_cncrd_adapter.enable }}
{{ $cncrdAdapterInput := dict "name" "payment-cncrd-adapter"
                         "all" .Values
                         "component" .Values.system.components.payment_cncrd_adapter
                         "secrets" (list "REG_SECRET_CONCARDIS_API_SECRET" "REG_SECRET_API_TOKEN" "REG_SECRET_CONCARDIS_INCOMING_WEBHOOK_SECRET" "REG_SECRET_DB_PASSWORD" )
                         "command" "/main"
                         "args" (list "--config=/config/config.yaml" "--migrate-database" "--ecs-json-logging") -}}
{{- template "helpers.deployment" $cncrdAdapterInput }}
---
{{- end }}
{{- if .Values.system.components.payment_service.enable }}
{{ $paySrvInput := dict "name" "payment-service"
                         "all" .Values
                         "component" .Values.system.components.payment_service
                         "secrets" (list "REG_SECRET_DB_PASSWORD" "REG_SECRET_API_TOKEN")
                         "command" "/main"
                         "args" (list "--config=/config/config.yaml" "--migrate-database" "--ecs-json-logging") -}}
{{- template "helpers.deployment" $paySrvInput }}
---
{{- end }}
{{- if .Values.system.components.regsys_classic.enable }}
{{ $classicInput := dict "name" "regsys-classic"
                         "all" .Values
                         "component" .Values.system.components.regsys_classic
                         "secrets" (list "REG_SECRET_API_TOKEN" "REG_SECRET_NOSECOUNTER_TOKEN" "REG_SECRET_DD_TOKEN" "REG_SECRET_ARTSHOW_TOKEN" "REG_SECRET_BOAT_TOKEN" "REG_SECRET_SECU_TOKEN" "REG_SECRET_SECU_SECRET")
                         "command" "/usr/bin/java"
                         "args" (list "-jar" "/app/regsys-classic.jar") -}}
{{- template "helpers.deployment" $classicInput }}
---
{{- end }}
{{- if .Values.system.components.frontend.enable }}
{{ $frontendInput := dict "name" "frontend"
                         "all" .Values
                         "component" .Values.system.components.frontend
                         "envs" (list "HTTPD_CONF_PATH_PREFIX_NO_SLASHES")
                         "command" "/usr/sbin/httpd"
                         "args" (list "-f" "/etc/apache2/regsys.conf" "-DNO_DETACH" "-DFOREGROUND")
                         "volume" "no" -}}
{{- template "helpers.deployment" $frontendInput }}
{{- end }}
