{{- if (.Values.ingress).enable }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: regsys-ingress
  {{- with .Values.global.namespace }}
  namespace: '{{ . }}'
  {{- end }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
  labels:
    {{- .Values.system.labels | toYaml | nindent 4 }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: frontend
                port:
                  number: 8080
{{- if .Values.ingress.tls.enable }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tls.secret_name }}
{{- end }}
---
{{- end }}
