{{- $attSrvInput := dict "name" "attendee-service"
                         "all" .Values
                         "component" .Values.system.components.attendee_service
                         "secrets" (list "REG_SECRET_DB_PASSWORD" "REG_SECRET_API_TOKEN") -}}
{{- template "helpers.deployment" $attSrvInput }}
