{{- $attSrvInput := dict "name" "attendee-service"
                         "all" .Values
                         "component" .Values.system.components.attendee_service -}}
{{- template "helpers.service" $attSrvInput }}
