name: Run Helm Unit-Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-helm-unit-tests:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: 'app'

      - name: Run Helm Unit Tests
        run: >
          cd app/charts/eurofurence-registration-system &&
          mkdir -p tests/__snapshot__ &&
          chmod 777 tests/__snapshot__ &&
          docker run --rm -v ${{ github.workspace }}/app/charts/eurofurence-registration-system:/apps helmunittest/helm-unittest:3.12.3-0.3.5 .
        shell: bash
